Repository IBM/Ansible-OpenShift-Provisioning, pull requests merged in 2024-03, with the labels that each got.

#242 Fix for - NAT vs IPForward documentation clarity #162
  docs/set-variables-group-vars.md
Labels: documentation

#248 fix: Mac specification documented but not in all.yaml.template.
  inventories/default/group_vars/all.yaml.template
Labels: bug, approved

#249 Deleting entries related to Bootstrap in Haproxy post its deletion
  playbooks/6_create_nodes.yaml
Labels: approved
